name: Weekly Scraper

on:
  schedule:
    - cron: '0 12 * * 0'  # Every Sunday at noon UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd scraper
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          cd services/scraper
          python main.py